name: picassostore
description: ""
publish_to: 'none'

version: 1.1.4+63

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.2
  intl: any
  http: ^1.1.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  mobile_scanner: ^6.0.1
  image_picker: ^1.1.2
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  freezed_annotation: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"